server:
  port: 8003
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/sys?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: "root"
      password: "gt040311"
      driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 5MB
    transaction:
      default-timeout: 30
      rollback-on-commit-failure: true
mybatis-plus:
  configuration:
      # 日志
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
      db-config:
        logic-delete-field: delFlag
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: auto
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.acm.entity